
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanage?useSSL=false&serverTimezone=UTC
    username: root
    password: lijinrun.com



Logging:
  level:
    com.wms: debug